version: "3.6"

services:
 serverlist:
  build: serverlist
  ports:
   - "8080:8080"

 minetest:
  image: registry.gitlab.com/minetest/minetest/server:5.7.0
  user: root
  volumes:
    - "minetest_home:/root/.minetest"
    - "./minetest.conf:/etc/minetest/minetest.conf"
  ports:
    - "30000:30000/udp"

volumes:
  minetest_home: {}