
mtt.register("serialize_json", function(callback)
    assert(announce.serialize_json("abc") == "\"abc\"")
    assert(announce.serialize_json(10) == "10")
    assert(announce.serialize_json(10.1) == "10.1")
    assert(announce.serialize_json(true) == "true")
    assert(announce.serialize_json(false) == "false")
    assert(announce.serialize_json(nil) == "null")
    assert(announce.serialize_json({}) == "[]")
    assert(announce.serialize_json({1,2,3}) == "[1,2,3]")
    assert(announce.serialize_json({"xy","z"}) == "[\"xy\",\"z\"]")
    assert(announce.serialize_json({x=2}) == "{\"x\":2}")
    callback()
end)